import type { QuizContentConfig } from "@/lib/quiz/quiz-content-types";

export const DEFAULT_QUIZ_CONTENT: QuizContentConfig = {
  sections: {
    energy: { title: "Read Your Energy", subtitle: "Calibrating your emotional rhythm." },
    social: { title: "Understand Your Vibe", subtitle: "Tuning social intent and mood direction." },
    flavor: { title: "Reveal Your Pairing", subtitle: "Mapping sensory preference and atmosphere." },
    taste: { title: "Taste Profiling", subtitle: "Capturing your sensory pull and finish." },
  },
  moodQuestions: [
    {
      id: "m1",
      section: "energy",
      role: "energy",
      prompt: "How’s your energy right now?",
      left: "Low / Drained",
      right: "High / Energized",
      active: true,
      sortOrder: 10,
    },
    {
      id: "m2",
      section: "energy",
      role: "emotion",
      prompt: "What best describes your mood?",
      left: "Heavy / Overwhelmed",
      right: "Light / Happy",
      active: true,
      sortOrder: 20,
    },
    {
      id: "m3",
      section: "energy",
      role: "mental",
      prompt: "How does your mind feel right now?",
      left: "Foggy / Tired",
      right: "Clear / Focused",
      active: true,
      sortOrder: 30,
    },
    {
      id: "m4",
      section: "social",
      role: "social",
      prompt: "What are you in the mood for socially?",
      left: "Be Alone",
      right: "Be Around People",
      active: true,
      sortOrder: 40,
    },
    {
      id: "m5",
      section: "social",
      role: "intent",
      prompt: "Right now, what do you want most?",
      left: "Disconnect / Reset",
      right: "Go Out / Celebrate",
      active: true,
      sortOrder: 50,
    },
    {
      id: "m6",
      section: "flavor",
      role: "intent",
      prompt: "What flavor direction feels right tonight?",
      left: "Deep / Smooth",
      right: "Crisp / Refreshing",
      active: true,
      sortOrder: 60,
    },
    {
      id: "m7",
      section: "flavor",
      role: "intent",
      prompt: "What atmosphere matches your energy?",
      left: "Quiet / Candlelight",
      right: "Neon / High Energy",
      active: true,
      sortOrder: 70,
    },
  ],
  tasteQuestions: [
    {
      id: "t1",
      section: "taste",
      prompt: "Which flavor hits hardest for you when you’re eating?",
      options: [
        { key: "A", text: "Bright, tangy, citrusy" },
        { key: "B", text: "Sweet, juicy, slightly candy-like" },
        { key: "C", text: "Warm, smooth, slightly spiced" },
      ],
      active: true,
      sortOrder: 110,
    },
    {
      id: "t2",
      section: "taste",
      prompt: "If you had to pick one, which would you reach for?",
      options: [
        { key: "A", text: "Lemon bar / key lime pie" },
        { key: "B", text: "Strawberry shortcake / fruit tart" },
        { key: "C", text: "Apple pie / baked dessert" },
      ],
      active: true,
      sortOrder: 120,
    },
    {
      id: "t3",
      section: "taste",
      prompt: "What texture do you enjoy most?",
      options: [
        { key: "A", text: "Crisp and refreshing" },
        { key: "B", text: "Light and juicy" },
        { key: "C", text: "Rich and smooth" },
      ],
      active: true,
      sortOrder: 130,
    },
    {
      id: "t4",
      section: "taste",
      prompt: "When you want something satisfying, you lean toward…",
      options: [
        { key: "A", text: "Something sharp and refreshing" },
        { key: "B", text: "Something sweet and uplifting" },
        { key: "C", text: "Something comforting and deep" },
      ],
      active: true,
      sortOrder: 140,
    },
    {
      id: "t5",
      section: "taste",
      prompt: "After you eat, what finish do you prefer?",
      options: [
        { key: "A", text: "Clean and slightly tangy" },
        { key: "B", text: "Sweet and lingering" },
        { key: "C", text: "Warm and rounded" },
      ],
      active: true,
      sortOrder: 150,
    },
  ],
};
